### ISSUE TITLE
Custom lib does not work

### ISSUE THREAD

**Issue by michalss** [Rohansi/Mond#103]
Hi i did try custom lib, but it seems there is some issue with init..

![image](https://user-images.githubusercontent.com/1000729/211185518-b9a14dc1-a2b8-4f43-9168-e8ee2b29a1f6.png)

![image](https://user-images.githubusercontent.com/1000729/211185529-22ad11db-a307-4606-81e3-f8c4e4ebdb4f.png)

So this aproach does not seems to work:
https://github.com/Rohansi/Mond/wiki/Custom-Libraries

I do have
```
   <PackageReference Include="Mond" Version="0.9.4" />
```

fyi @Rohansi

**Comment by michalss** [comment]
My goal in here is do define own functions written in c# to use in Mond without globals.

**Comment by michalss** [comment]
I did eve try sample from wiki page, same result, it simply does not work...

**Comment by SirTony** [comment]
It's giving you an error because you're missing the braces when assigning the `Libraries` property.

The `Libraries` property is an instance of [MondLibraryManager](https://github.com/Rohansi/Mond/blob/97035248dd8568cd84b074556d9a85e14feeb67e/Mond/Libraries/MondLibraryManager.cs), and in your example you are attempting to replace `MondLibraryManager` with `MondCustomLibrary`, in this case you want to add your class to the library manager using the [collection initializer](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers).

```csharp
private MondState state = new MondState
{
    Libraries =
    { // <-- the brace uses the collection initializer
        new MondCustomLibrary(),
    } // <-- end collection initializer
};
```

This is consistent with the example on the wiki

```csharp
var state = new MondState
{
    Libraries =
    {
        new MyAwesomeLibrary(),
    }
};
```

**Comment by michalss** [comment]
Damn im so sorry i missed the baces, feell stupid :( sorry..
