### ISSUE TITLE
How to convert string to number in Mond ?

### ISSUE THREAD

**Issue by michalss** [Rohansi/Mond#112]
Hello,

Si there a way to convert string to number in Mond please?

regards

**Comment by Rohansi** [comment]
There... wasn't anything built in for that! 😅  I have added it now and pushed out version 0.10.2. When you update you'll find [these functions](https://github.com/Rohansi/Mond/wiki/Parse-Library) are now available.

Also note that I combined Mond.SourceGenerator into the Mond NuGet package. When updating to 0.10.2 you should remove Mond.SourceGenerator from your installed packages because it will already be included in Mond 0.10.2.
